# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import joblib

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 20)

import warnings
warnings.filterwarnings("ignore")

# Setting Project Directories

In [2]:
CURRENT_DIR = Path.cwd()

PROJECT_ROOT = CURRENT_DIR.parent

DATA_DIR = PROJECT_ROOT / "data"

RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
ARTIFACT_DIR = DATA_DIR / "artifacts"

print(PROJECT_ROOT)
print(RAW_DATA_DIR)

c:\Jupyter Notebook\PROJECTS\Breast_cancer_analysis
c:\Jupyter Notebook\PROJECTS\Breast_cancer_analysis\data\raw

# Loading Dataset

In [3]:
dataset_path = RAW_DATA_DIR / "Breast_GSE45827.csv"

df = pd.read_csv(dataset_path)

# Basic Inspection

In [4]:
print(df.shape)

(151, 54677)

In [5]:
df.head()

,samples,type,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,1438_at,1487_at,1494_f_at,1552256_a_at,1552257_a_at,1552258_at,1552261_at,1552263_at,1552264_a_at,1552266_at,1552269_at,1552271_at,1552272_a_at,1552274_at,1552275_s_at,1552276_a_at,1552277_a_at,1552278_a_at,1552279_a_at,1552280_at,1552281_at,1552283_s_at,1552286_at,1552287_s_at,1552288_at,1552289_a_at,1552291_at,1552293_at,1552295_a_at,1552296_at,1552299_at,1552301_a_at,1552302_at,1552303_a_at,1552304_at,1552306_at,1552307_a_at,1552309_a_at,...,AFFX-HSAC07/X00351_3_at,AFFX-HSAC07/X00351_5_at,AFFX-HSAC07/X00351_M_at,AFFX-hum_alu_at,AFFX-HUMGAPDH/M33197_3_at,AFFX-HUMGAPDH/M33197_5_at,AFFX-HUMGAPDH/M33197_M_at,AFFX-HUMISGF3A/M97935_3_at,AFFX-HUMISGF3A/M97935_5_at,AFFX-HUMISGF3A/M97935_MA_at,AFFX-HUMISGF3A/M97935_MB_at,AFFX-HUMRGE/M10098_3_at,AFFX-HUMRGE/M10098_5_at,AFFX-HUMRGE/M10098_M_at,AFFX-LysX-3_at,AFFX-LysX-5_at,AFFX-LysX-M_at,AFFX-M27830_3_at,AFFX-M27830_5_at,AFFX-M27830_M_at,AFFX-PheX-3_at,AFFX-PheX-5_at,AFFX-PheX-M_at,AFFX-r2-Bs-dap-3_at,AFFX-r2-Bs-dap-5_at,AFFX-r2-Bs-dap-M_at,AFFX-r2-Bs-lys-3_at,AFFX-r2-Bs-lys-5_at,AFFX-r2-Bs-lys-M_at,AFFX-r2-Bs-phe-3_at,AFFX-r2-Bs-phe-5_at,AFFX-r2-Bs-phe-M_at,AFFX-r2-Bs-thr-3_s_at,AFFX-r2-Bs-thr-5_s_at,AFFX-r2-Bs-thr-M_s_at,AFFX-r2-Ec-bioB-3_at,AFFX-r2-Ec-bioB-5_at,AFFX-r2-Ec-bioB-M_at,AFFX-r2-Ec-bioC-3_at,AFFX-r2-Ec-bioC-5_at,AFFX-r2-Ec-bioD-3_at,AFFX-r2-Ec-bioD-5_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,84,basal,9.850040,8.097927,6.424728,7.353027,3.029122,6.880079,4.963740,4.408328,8.870780,3.278896,7.317273,6.941792,4.753893,9.689422,9.529578,4.416768,4.061347,6.468291,8.671009,3.766666,3.711459,5.076329,4.442042,6.741298,5.627442,5.516712,8.107136,4.956239,5.791279,3.569233,5.687476,4.152096,4.906925,8.206707,4.463950,5.186044,5.942088,4.191142,7.413500,3.281950,4.346253,3.883254,5.143185,5.953880,3.809545,4.903795,6.163062,5.960296,...,13.617425,13.334689,13.611892,14.617621,13.620367,13.816580,13.953181,10.944267,8.018416,9.566412,9.015007,12.050521,14.750905,13.359472,5.576968,3.606041,4.481027,5.509117,10.544533,11.200692,5.932332,4.253946,5.052679,7.782348,7.056759,7.787824,4.784976,3.943038,3.903069,6.119248,4.461984,4.752744,6.761262,5.298281,6.048960,8.292124,8.225293,8.333853,9.854639,9.823275,12.229711,11.852955,13.658701,13.477698,6.265781,5.016196,4.901594,2.966657,3.508495,3.301999
1,85,basal,9.861357,8.212222,7.062593,7.685578,3.149468,7.542283,5.129607,4.584418,7.767646,3.589636,8.768129,7.567034,4.859823,8.459354,8.973671,4.503730,5.390424,6.756707,8.105795,4.651541,3.935309,5.228763,4.454780,6.468014,5.798596,5.306064,7.505800,4.636866,5.898319,3.749061,5.582313,4.449042,5.871074,7.242601,3.938327,4.378953,6.294126,4.058221,6.799876,3.004077,5.170231,3.915350,5.618675,6.103758,3.468310,3.805643,5.059153,7.665774,...,13.724468,13.150684,13.449886,14.718935,13.650388,13.720148,13.877805,11.397179,8.665182,10.400595,9.371174,8.264719,9.938357,9.507651,6.103962,3.983087,4.742306,5.424172,8.881772,11.148811,6.330691,4.755615,5.474167,8.542725,7.617779,8.237535,5.209694,3.939264,4.553344,6.017351,5.425393,4.957182,7.405313,5.615380,6.617585,8.225366,8.409790,8.499343,10.061910,9.796947,12.178531,11.809408,13.750086,13.470146,6.771853,5.291005,5.405839,2.934763,3.687666,3.064299
2,87,basal,10.103478,8.936137,5.735970,7.687822,3.125931,6.562369,4.813449,4.425195,9.417956,3.552253,7.945085,7.238284,4.872635,9.367521,9.133688,4.358608,4.445164,5.476936,8.752115,3.546838,4.263868,5.509159,4.624205,7.103216,6.641263,5.141131,7.072525,4.728196,6.233648,3.766725,6.008163,4.191390,5.717077,7.809222,4.108028,5.012451,7.258626,4.330997,6.901454,4.032173,4.203554,4.133019,4.262457,4.463875,3.533392,4.019280,5.058569,5.264810,...,13.484744,13.095263,13.307587,14.560461,14.012596,14.186929,14.372375,10.853229,8.196331,9.569712,8.842430,10.241912,13.605901,11.784269,5.853014,3.748889,4.407490,5.919699,9.687444,11.601339,6.040000,4.314678,5.274790,8.030696,7.082369,7.912491,4.725483,4.036020,4.141341,5.825904,5.032693,4.764559,7.026349,5.448507,6.386042,8.218749,8.209361,8.280136,9.699647,9.452066,12.125108,11.725766,13.621732,13.295080,6.346952,5.171403,5.184286,2.847684,3.550597,3.158535
3,90,basal,9.756875,7.357148,6.479183,6.986624,3.181638,7.802344,5.490982,4.567956,9.022345,3.312473,7.754670,7.078843,4.867320,7.790225,7.206228,4.680283,4.171577,5.985232,7.205984,3.568459,3.310109,5.166409,4.160049,6.730255,5.774961,6.092539,7.164589,4.903609,5.726683,3.532517,5.652934,3.997426,6.151148,7.189197,4.329053,5.134634,6.300199,4.192591,7.082357,3.249017,5.053049,4.326114,6.433557,6.290000,3.541128,4.204941,5.724873,5.942604,...,13.551811,12.832413,13.117943,14.665369,13.132551,13.085546,13.162920,12.506467,9.930142,11.539292,10.554449,9.191622,12.146083,11.018158,5.972863,3.658838,4.657377,5.508931,9.262102,11.338670,6.194179,4.300024,5.072087,8.148625,7.548858,7.960282,5.226375,3.562438,4.306947,5.979139,5.018239,4.872679,7.066764,5.573531,6.637775,8.183538,8.307374,8.233631,9.911691,9.611842,12.111235,11.719215,13.743108,13.508861,6.610284,5.193356,5.086569,3.031602,3.524981,3.272665
4,91,basal,9.408330,7.746404,6.693980,7.333426,3.169923,7.610457,5.372469,4.424426,9.400056,3.368243,9.052192,6.889370,4.939912,8.432573,9.240390,4.689763,4.224431,6.386138,7.732480,4.233807,4.392973,5.265164,4.161808,6.984456,6.219122,5.187331,8.225413,5.238370,6.165456,3.500029,5.694598,4.298906,5.211584,7.708507,4.991938,5.860185,6.217526,3.997529,7.031443,3.633830,3.493578,4.277560,6.577723,6.452748,3.500522,3.949983,5.356630,7.220105,...,13.722927,13.074863,13.382671,14.686639,13.566575,13.651270,13.695763,11.711930,8.710942,10.481122,9.660223,11.501202,12.598456,11.611006,5.763398,3.517613,4.514921,5.498137,9.336550,11.446506,6.072134,4.312846,5.167958,8.179727,7.501891,7.931099,4.897629,3.710210,3.953584,5.928464,4.910085,4.671537,7.011404,5.452125,6.349551,8.307028,8.440426,8.319234,9.868997,9.655341,12.173642,11.861296,13.797774,13.542206,6.414354,5.040202,5.235318,2.956232,3.445501,3.193947

In [6]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Columns: 54677 entries, samples to AFFX-TrpnX-M_at
dtypes: float64(54675), int64(1), object(1)
memory usage: 63.0 MB

In [7]:
print(df.dtypes)

samples              int64
type                object
1007_s_at          float64
1053_at            float64
117_at             float64
                    ...
AFFX-ThrX-5_at     float64
AFFX-ThrX-M_at     float64
AFFX-TrpnX-3_at    float64
AFFX-TrpnX-5_at    float64
AFFX-TrpnX-M_at    float64
Length: 54677, dtype: object

In [8]:
float_cols = df.select_dtypes(include=["float64"]).columns

df[float_cols] = df[float_cols].astype(np.float32)

print("Optimization complete.")

Optimization complete.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Columns: 54677 entries, samples to AFFX-TrpnX-M_at
dtypes: float32(54675), int64(1), object(1)
memory usage: 31.5+ MB

In [10]:
df = df.drop('samples', axis = 'columns')

#### i want to remove the non-cancer/artificial categories (normal, cell_line) and keep only actual cancer subtypes

In [11]:
df = df[~df['type'].isin(['normal', 'cell_line'])]
df = df.reset_index(drop=True)

In [13]:
print(df['type'].value_counts())

type
basal        41
HER          30
luminal_B    30
luminal_A    29
Name: count, dtype: int64

In [12]:
df.head()

,type,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,1438_at,1487_at,1494_f_at,1552256_a_at,1552257_a_at,1552258_at,1552261_at,1552263_at,1552264_a_at,1552266_at,1552269_at,1552271_at,1552272_a_at,1552274_at,1552275_s_at,1552276_a_at,1552277_a_at,1552278_a_at,1552279_a_at,1552280_at,1552281_at,1552283_s_at,1552286_at,1552287_s_at,1552288_at,1552289_a_at,1552291_at,1552293_at,1552295_a_at,1552296_at,1552299_at,1552301_a_at,1552302_at,1552303_a_at,1552304_at,1552306_at,1552307_a_at,1552309_a_at,1552310_at,...,AFFX-HSAC07/X00351_3_at,AFFX-HSAC07/X00351_5_at,AFFX-HSAC07/X00351_M_at,AFFX-hum_alu_at,AFFX-HUMGAPDH/M33197_3_at,AFFX-HUMGAPDH/M33197_5_at,AFFX-HUMGAPDH/M33197_M_at,AFFX-HUMISGF3A/M97935_3_at,AFFX-HUMISGF3A/M97935_5_at,AFFX-HUMISGF3A/M97935_MA_at,AFFX-HUMISGF3A/M97935_MB_at,AFFX-HUMRGE/M10098_3_at,AFFX-HUMRGE/M10098_5_at,AFFX-HUMRGE/M10098_M_at,AFFX-LysX-3_at,AFFX-LysX-5_at,AFFX-LysX-M_at,AFFX-M27830_3_at,AFFX-M27830_5_at,AFFX-M27830_M_at,AFFX-PheX-3_at,AFFX-PheX-5_at,AFFX-PheX-M_at,AFFX-r2-Bs-dap-3_at,AFFX-r2-Bs-dap-5_at,AFFX-r2-Bs-dap-M_at,AFFX-r2-Bs-lys-3_at,AFFX-r2-Bs-lys-5_at,AFFX-r2-Bs-lys-M_at,AFFX-r2-Bs-phe-3_at,AFFX-r2-Bs-phe-5_at,AFFX-r2-Bs-phe-M_at,AFFX-r2-Bs-thr-3_s_at,AFFX-r2-Bs-thr-5_s_at,AFFX-r2-Bs-thr-M_s_at,AFFX-r2-Ec-bioB-3_at,AFFX-r2-Ec-bioB-5_at,AFFX-r2-Ec-bioB-M_at,AFFX-r2-Ec-bioC-3_at,AFFX-r2-Ec-bioC-5_at,AFFX-r2-Ec-bioD-3_at,AFFX-r2-Ec-bioD-5_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,basal,9.850040,8.097927,6.424728,7.353027,3.029122,6.880079,4.963740,4.408328,8.870780,3.278896,7.317273,6.941792,4.753893,9.689422,9.529577,4.416768,4.061347,6.468291,8.671009,3.766666,3.711459,5.076329,4.442042,6.741298,5.627442,5.516712,8.107137,4.956239,5.791278,3.569233,5.687476,4.152096,4.906925,8.206707,4.463950,5.186044,5.942088,4.191142,7.413500,3.281950,4.346253,3.883254,5.143185,5.953880,3.809546,4.903795,6.163062,5.960296,6.503104,...,13.617425,13.334688,13.611892,14.617621,13.620367,13.816580,13.953181,10.944267,8.018416,9.566412,9.015007,12.050521,14.750905,13.359472,5.576968,3.606041,4.481027,5.509117,10.544533,11.200692,5.932332,4.253946,5.052680,7.782348,7.056759,7.787824,4.784976,3.943038,3.903069,6.119248,4.461984,4.752744,6.761262,5.298281,6.048960,8.292124,8.225292,8.333854,9.854639,9.823276,12.229711,11.852955,13.658701,13.477698,6.265781,5.016196,4.901594,2.966657,3.508495,3.301999
1,basal,9.861358,8.212222,7.062593,7.685578,3.149468,7.542283,5.129607,4.584418,7.767646,3.589636,8.768128,7.567034,4.859823,8.459353,8.973671,4.503730,5.390424,6.756707,8.105795,4.651541,3.935309,5.228763,4.454780,6.468014,5.798596,5.306064,7.505800,4.636866,5.898319,3.749061,5.582313,4.449042,5.871074,7.242601,3.938327,4.378953,6.294126,4.058221,6.799876,3.004077,5.170231,3.915350,5.618675,6.103758,3.468310,3.805643,5.059153,7.665774,6.230720,...,13.724468,13.150683,13.449886,14.718935,13.650388,13.720148,13.877806,11.397179,8.665182,10.400596,9.371175,8.264719,9.938356,9.507651,6.103961,3.983088,4.742306,5.424171,8.881772,11.148811,6.330691,4.755615,5.474167,8.542725,7.617779,8.237535,5.209694,3.939264,4.553344,6.017351,5.425393,4.957181,7.405313,5.615380,6.617585,8.225366,8.409790,8.499343,10.061910,9.796947,12.178531,11.809408,13.750086,13.470146,6.771852,5.291005,5.405838,2.934763,3.687666,3.064299
2,basal,10.103478,8.936137,5.735970,7.687822,3.125932,6.562369,4.813449,4.425195,9.417956,3.552253,7.945086,7.238284,4.872635,9.367521,9.133688,4.358608,4.445164,5.476936,8.752114,3.546838,4.263868,5.509159,4.624205,7.103216,6.641263,5.141131,7.072525,4.728196,6.233648,3.766725,6.008163,4.191391,5.717077,7.809222,4.108028,5.012451,7.258626,4.330997,6.901454,4.032173,4.203554,4.133018,4.262457,4.463875,3.533392,4.019280,5.058569,5.264810,5.795663,...,13.484744,13.095263,13.307587,14.560461,14.012596,14.186929,14.372375,10.853230,8.196331,9.569713,8.842430,10.241912,13.605902,11.784268,5.853014,3.748889,4.407490,5.919699,9.687445,11.601338,6.040000,4.314678,5.274790,8.030696,7.082369,7.912491,4.725483,4.036020,4.141341,5.825904,5.032693,4.764559,7.026350,5.448506,6.386042,8.218749,8.209361,8.280136,9.699647,9.452066,12.125109,11.725766,13.621733,13.295080,6.346952,5.171403,5.184286,2.847684,3.550597,3.158535
3,basal,9.756875,7.357148,6.479183,6.986624,3.181638,7.802344,5.490982,4.567956,9.022346,3.312473,7.754670,7.078843,4.867321,7.790225,7.206228,4.680283,4.171577,5.985232,7.205984,3.568459,3.310109,5.166409,4.160049,6.730255,5.774961,6.092539,7.164589,4.903609,5.726683,3.532517,5.652934,3.997426,6.151148,7.189197,4.329053,5.134634,6.300199,4.192591,7.082357,3.249017,5.053049,4.326114,6.433557,6.290000,3.541128,4.204941,5.724873,5.942604,6.008364,...,13.551811,12.832414,13.117943,14.665369,13.132551,13.085546,13.162920,12.506467,9.930142,11.539291,10.554449,9.191623,12.146083,11.018158,5.972863,3.658838,4.657377,5.508931,9.262102,11.338670,6.194180,4.300025,5.072087,8.148625,7.548858,7.960282,5.226375,3.562438,4.306947,5.979139,5.018239,4.872679,7.066763,5.573531,6.637775,8.183537,8.307374,8.233631,9.911691,9.611842,12.111235,11.719215,13.743108,13.508861,6.610283,5.193356,5.086569,3.031602,3.524981,3.272665
4,basal,9.408330,7.746404,6.693980,7.333426,3.169923,7.610457,5.372469,4.424426,9.400056,3.368243,9.052192,6.889370,4.939911,8.432572,9.240391,4.689763,4.224431,6.386138,7.732480,4.233808,4.392973,5.265164,4.161808,6.984456,6.219122,5.187331,8.225412,5.238370,6.165456,3.500029,5.694598,4.298906,5.211584,7.708507,4.991938,5.860185,6.217526,3.997530,7.031443,3.633830,3.493578,4.277561,6.577723,6.452747,3.500522,3.949983,5.356629,7.220105,8.160023,...,13.722926,13.074862,13.382670,14.686639,13.566575,13.651270,13.695763,11.711929,8.710941,10.481122,9.660223,11.501203,12.598455,11.611007,5.763398,3.517613,4.514921,5.498137,9.336550,11.446507,6.072134,4.312846,5.167958,8.179727,7.501891,7.931099,4.897629,3.710210,3.953584,5.928464,4.910085,4.671537,7.011404,5.452125,6.349551,8.307028,8.440426,8.319234,9.868997,9.655341,12.173642,11.861296,13.797774,13.542206,6.414354,5.040202,5.235318,2.956232,3.445501,3.193947

# Exporting Optimized Artifact

In [14]:
parquet_path = PROCESSED_DATA_DIR / "breast_cancer.parquet"

df.to_parquet(parquet_path, index=False)

print(f"Saved to: {parquet_path}")

Saved to: c:\Jupyter Notebook\PROJECTS\Breast_cancer_analysis\data\processed\breast_cancer.parquet